FROM node:16 as build
WORKDIR /app
COPY ./src /app/src
COPY ./angular.json /app/angular.json
RUN npm install && ng build --prod

FROM nginx:alpine
COPY --from=build /app/dist/ElearningManagement /usr/share/nginx/html
EXPOSE 80
