apiVersion: v1
kind: Service
metadata:
  name: LMS-Portal-FService
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 4200
    protocol: TCP
  selector:
    app: angular-lms-portal
