apiVersion: v1
kind: Service
metadata:
  name: LMS-Portal-Service
spec:
  type: NodePort
  selector:
    app: spring-boot-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  